interface Question {
  text: string;
  unit: string;
}

export const questions: Question[] = [
  {
    text: "What is the world record for holding your breath",
    unit: "seconds",
  },
  {
    text: "How many hours did the developer spend making this game",
    unit: "hours",
  },
  {
    text: "How many unarmed humans would it take to kill a T-Rex",
    unit: "Humans",
  },
  {
    text: "How many times have you fallen in love",
    unit: "times",
  },
  {
    text: "How many words are in the Harry Potter series",
    unit: "words",
  },
  {
    text: "How many pushups could you do right now",
    unit: "pushups",
  },
  {
    text: "How far is Boston from San Francisco",
    unit: "miles",
  },
  {
    text:
      "How much money would #player need to be paid to eat only dry salads for a year",
    unit: "dollars",
  },
  {
    text: "On a scale of 1-100 how much are you enjoying this game?",
    unit: "enjoyment units",
  },
  {
    text: "How many first dates have you been on",
    unit: "dates",
  },
  {
    text: "On a scale of 1-100 how do you feel today",
    unit: "feelings",
  },
  {
    text: "What year in the past would you visit if you could?",
    unit: "year",
  },
  {
    text: "How many slices of pizza is like too much pizza at one time",
    unit: "slices of pizza",
  },
  {
    text:
      "What is the minimum number of people needed for a low key hang to be considered a party",
    unit: "chill hangers",
  },
  {
    text: "What's the most money you've ever won gambling",
    unit: "ill beggotten gains",
  },
  {
    text: "What is your monthly grocery bill",
    unit: "dollars",
  },
  {
    text: "How many minutes do you take to eat dinner",
    unit: "minutes",
  },
  {
    text: "How many cups of coffee do you drink a day",
    unit: "cups of coffee",
  },
  {
    text: "How many miles could you walk in one day",
    unit: "miles",
  },
  {
    text: "enter a random number you like between 1 and 1000",
    unit: "this one is stupid we know lol",
  },
  {
    text: "How many years until we have self driving cars",
    unit: "years",
  },
  {
    text:
      "Consider the following. You are standing outside a walmart entrance. You need to go in and find 1. a copy of wedding crashers on dvd, 2. a blanket and 3. a tub of cheesy poofs. Then you need to pay for everything and exit the walmart. How many minutes would that take you going as fast as possible ",
    unit: "minutes",
  },
  {
    text: "What time do you go to sleep? use 24 hour notation",
    unit: "hours",
  },
  {
    text: "How many angels can dance on the head of a pin",
    unit: "Angels",
  },
  {
    text: "How much money would you pay for this game",
    unit: "dollars",
  },
  {
    text: "How many languages are spoken in india",
    unit: "Languages",
  },
  //Google autogenerated questions
  { text: "How many arms does a squid have", unit: "arms" },
  {
    text:
      "What do you think you would score on the SAT if you took it right now",
    unit: "points",
  },
  { text: "How many astronauts have walked on the moon", unit: "astronauts" },
  { text: "How many albums does Taylor Swift have", unit: "albums" },
  { text: "How many Avengers are there", unit: "Avengers" },
  { text: "How many quarters in a roll", unit: "quarters" },
  { text: "How many wives did Henry viii have", unit: "wives" },
  {
    text: "How many words per minute do you type",
    unit: "words",
  },
  { text: "How many wars has the USA lost", unit: "wars" },
  { text: "How many drinks before you are drunk", unit: "drinks" },
  { text: "How many electoral votes are there", unit: "electoral votes" },
  { text: "How many ewoks died on the battle of endor", unit: "ewoks" },
  { text: "How many grams in an ounce", unit: "grams" },
  { text: "How many eggs does a chicken lay in a year", unit: "eggs" },
  { text: "How many employees does Amazon have", unit: "Employees" },
  { text: "How many rings does Lebron James have", unit: "rings" },
  //End google
  { text: "How much should you spend on a big night out", unit: "dollars" },
];
