import { IQuestion } from "./types/IQuestion";

// sfw: safe to play with coworkers (the "corporate" pool). The full pool is
// everything below; keep new questions PG-13 either way.
export const questions: IQuestion[] = [
  {
    text: "What is the world record for holding your breath",
    unit: "seconds",
    sfw: true,
  },
  {
    text: "How many hours did the developer spend making this game",
    unit: "hours",
    sfw: true,
  },
  {
    text: "How many unarmed humans would it take to kill a T-Rex",
    unit: "Humans",
    sfw: true,
  },
  {
    text: "How many times have you fallen in love",
    unit: "times",
    sfw: false,
  },
  {
    text: "How many words are in the Harry Potter series",
    unit: "words",
    sfw: true,
  },
  {
    text: "How many pushups could you do right now",
    unit: "pushups",
    sfw: true,
  },
  {
    text: "How far is Boston from San Francisco",
    unit: "miles",
    sfw: true,
  },
  {
    text:
      "How much money would #player need to be paid to eat only dry salads for a year",
    unit: "dollars",
    sfw: true,
  },
  {
    text: "On a scale of 1-100 how much are you enjoying this game?",
    unit: "enjoyment units",
    sfw: true,
  },
  {
    text: "How many first dates have you been on",
    unit: "dates",
    sfw: false,
  },
  {
    text: "On a scale of 1-100 how do you feel today",
    unit: "feelings",
    sfw: true,
  },
  {
    text: "What year in the past would you visit if you could?",
    unit: "year",
    sfw: true,
  },
  {
    text: "How many slices of pizza is like too much pizza at one time",
    unit: "slices of pizza",
    sfw: true,
  },
  {
    text:
      "What is the minimum number of people needed for a low key hang to be considered a party",
    unit: "chill hangers",
    sfw: true,
  },
  {
    text: "What's the most money you've ever won gambling",
    unit: "ill beggotten gains",
    sfw: false,
  },
  {
    text: "What is your monthly grocery bill",
    unit: "dollars",
    sfw: true,
  },
  {
    text: "How many minutes do you take to eat dinner",
    unit: "minutes",
    sfw: true,
  },
  {
    text: "How many cups of coffee do you drink a day",
    unit: "cups of coffee",
    sfw: true,
  },
  {
    text: "How many miles could you walk in one day",
    unit: "miles",
    sfw: true,
  },
  {
    text: "enter a random number you like between 1 and 1000",
    unit: "this one is stupid we know lol",
    sfw: true,
  },
  {
    text: "How many years until we have self driving cars",
    unit: "years",
    sfw: true,
  },
  {
    text:
      "Consider the following. You are standing outside a walmart entrance. You need to go in and find 1. a copy of wedding crashers on dvd, 2. a blanket and 3. a tub of cheesy poofs. Then you need to pay for everything and exit the walmart. How many minutes would that take you going as fast as possible ",
    unit: "minutes",
    sfw: true,
  },
  {
    text: "What time do you go to sleep? use 24 hour notation",
    unit: "hours",
    sfw: true,
  },
  {
    text: "How many angels can dance on the head of a pin",
    unit: "Angels",
    sfw: true,
  },
  {
    text: "How much money would you pay for this game",
    unit: "dollars",
    sfw: true,
  },
  {
    text: "How many languages are spoken in india",
    unit: "Languages",
    sfw: true,
  },
  //Google autogenerated questions
  { text: "How many arms does a squid have", unit: "arms", sfw: true },
  {
    text:
      "What do you think you would score on the SAT if you took it right now",
    unit: "points",
    sfw: true,
  },
  {
    text: "How many astronauts have walked on the moon",
    unit: "astronauts",
    sfw: true,
  },
  {
    text: "How many albums does Taylor Swift have",
    unit: "albums",
    sfw: true,
  },
  { text: "How many Avengers are there", unit: "Avengers", sfw: true },
  { text: "How many quarters in a roll", unit: "quarters", sfw: true },
  { text: "How many wives did Henry viii have", unit: "wives", sfw: true },
  {
    text: "How many words per minute do you type",
    unit: "words",
    sfw: true,
  },
  { text: "How many wars has the USA lost", unit: "wars", sfw: true },
  {
    text: "How many drinks before you are drunk",
    unit: "drinks",
    sfw: false,
  },
  {
    text: "How many electoral votes are there",
    unit: "electoral votes",
    sfw: true,
  },
  {
    text: "How many ewoks died on the battle of endor",
    unit: "ewoks",
    sfw: true,
  },
  { text: "How many grams in an ounce", unit: "grams", sfw: true },
  {
    text: "How many eggs does a chicken lay in a year",
    unit: "eggs",
    sfw: true,
  },
  {
    text: "How many employees does Amazon have",
    unit: "Employees",
    sfw: true,
  },
  {
    text: "How many rings does Lebron James have",
    unit: "rings",
    sfw: true,
  },
  //End google
  {
    text: "How much should you spend on a big night out",
    unit: "dollars",
    sfw: false,
  },
  // 2026 revival batch
  {
    text:
      "how many alarms do you have set on your phone right now, including the graveyard of disabled ones",
    unit: "alarms",
    sfw: true,
  },
  {
    text:
      "how many minutes a day does #player spend on the toilet just scrolling their phone",
    unit: "porcelain minutes",
    sfw: false,
  },
  {
    text:
      "how many times a day do you open the fridge hoping new food has spawned since the last check",
    unit: "fridge pilgrimages",
    sfw: true,
  },
  {
    text:
      "how many slices of pizza could #player put away in one sitting if absolutely nobody was watching",
    unit: "shameless slices",
    sfw: true,
  },
  {
    text:
      "what's your personal record for consecutive days wearing the same hoodie before washing it",
    unit: "hoodie days",
    sfw: true,
  },
  {
    text:
      "how many screenshots are on your phone that you have never once looked at again",
    unit: "forgotten screenshots",
    sfw: true,
  },
  {
    text:
      "how many dishes are in your sink at this exact moment",
    unit: "shame dishes",
    sfw: true,
  },
  {
    text:
      "how old is the oldest condiment in your fridge, in years",
    unit: "condiment years",
    sfw: true,
  },
  {
    text:
      "a mysterious benefactor offers to handle #player's laundry forever — washed, folded, delivered — how many dollars a month would they actually pay for it",
    unit: "laundry dollars per month",
    sfw: true,
  },
  {
    text:
      "how many times a week do you announce you're going to bed and then stay up another hour",
    unit: "bedtime lies",
    sfw: true,
  },
  {
    text:
      "the grocery stores all close forever tomorrow — how many days could #player survive on only what's in their kitchen right now",
    unit: "cupboard days",
    sfw: true,
  },
  {
    text:
      "how many angry geese could #player fend off with a single pool noodle before going down",
    unit: "geese",
    sfw: true,
  },
  {
    text:
      "how many duck-sized horses could you defeat in open combat before the tiny hooves overwhelm you",
    unit: "duck-sized horses",
    sfw: true,
  },
  {
    text:
      "a bear is chasing you but it's riding a tricycle. how many seconds of head start do you need to survive",
    unit: "seconds of head start",
    sfw: true,
  },
  {
    text:
      "how many days could you secretly live inside an ikea before an employee noticed",
    unit: "days of ikea residency",
    sfw: true,
  },
  {
    text:
      "how many fully cooperating pigeons would it take to lift you off the ground",
    unit: "team-player pigeons",
    sfw: true,
  },
  {
    text:
      "you wake up as a t-rex in your own home. how many minutes until you accidentally destroy something you truly love",
    unit: "minutes of tiny-armed chaos",
    sfw: true,
  },
  {
    text:
      "how many hours would #player stay hidden from a squad of 40 professionally trained hide-and-seek toddlers",
    unit: "hours undetected",
    sfw: true,
  },
  {
    text:
      "how many golden retrievers hitched to a sled would it take to drag you out of waist-deep quicksand",
    unit: "golden retrievers",
    sfw: true,
  },
  {
    text:
      "how many dollars would it take for you to spend one full night alone in a wax museum",
    unit: "wax museum dollars",
    sfw: true,
  },
  {
    text:
      "how many ducks in a trenchcoat would it take to convincingly cover #player's job for one day",
    unit: "trenchcoat ducks",
    sfw: true,
  },
  {
    text:
      "a wizard swears every hot dog you eat adds one day to your life. how many do you get through in one sitting",
    unit: "life-extending hot dogs",
    sfw: true,
  },
  {
    text:
      "you're stranded on a desert island with unlimited coconuts and one volleyball. how many days before you give the volleyball a name and a full backstory",
    unit: "days until wilson",
    sfw: true,
  },
  {
    text:
      "how many minutes would you stay on your feet in a boxing ring with one mildly annoyed kangaroo",
    unit: "minutes on your feet",
    sfw: true,
  },
  {
    text:
      "how many beers deep would #player need to be to genuinely believe they could beat up a swan",
    unit: "beers of false confidence",
    sfw: false,
  },
  {
    text:
      "the zombie apocalypse hits. how many exes do you go back and rescue before saving yourself",
    unit: "rescued exes",
    sfw: false,
  },
  {
    text:
      "how many escalators are there in the entire state of wyoming",
    unit: "escalators",
    sfw: true,
  },
  {
    text:
      "in 2018 a team of volunteers counted every squirrel in central park. how many did they find",
    unit: "census squirrels",
    sfw: true,
  },
  {
    text:
      "how many teeth does the average garden snail have",
    unit: "tiny snail teeth",
    sfw: true,
  },
  {
    text:
      "how many helium party balloons would it take to lift #player off the ground like in that pixar movie",
    unit: "balloons",
    sfw: true,
  },
  {
    text:
      "how many inches taller does the eiffel tower get on a hot summer day",
    unit: "inches of summer stretch",
    sfw: true,
  },
  {
    text:
      "how many golf balls would it take to completely fill a standard bathtub",
    unit: "golf balls",
    sfw: true,
  },
  {
    text:
      "how much does an average fluffy cumulus cloud weigh in pounds",
    unit: "pounds of fluff",
    sfw: true,
  },
  {
    text:
      "in 1992 a shipping container of rubber ducks fell into the pacific ocean and they are still washing ashore. how many ducks escaped",
    unit: "fugitive ducks",
    sfw: true,
  },
  {
    text:
      "how many miles of bookshelves does the library of congress have",
    unit: "miles of shelves",
    sfw: true,
  },
  {
    text:
      "#player decides to walk clear across rhode island the short way. how many steps does that take",
    unit: "steps",
    sfw: true,
  },
  {
    text:
      "how many cows are standing within 50 miles of #player right now",
    unit: "nearby cows",
    sfw: true,
  },
  {
    text:
      "how many individual socks will the average person lose to the laundry over a lifetime",
    unit: "socks gone forever",
    sfw: true,
  },
  {
    text:
      "how many working satellites are circling the earth at this exact moment",
    unit: "satellites overhead",
    sfw: true,
  },
  {
    text:
      "if every tree on earth got split evenly between every living human, how many trees would each of us get",
    unit: "personal trees",
    sfw: true,
  },
  {
    text:
      "how many times has your heart beaten since you woke up this morning",
    unit: "heartbeats",
    sfw: true,
  },
  {
    text:
      "how many unread emails are rotting in your inbox right now",
    unit: "rotting emails",
    sfw: true,
  },
  {
    text:
      "how many minutes would #player survive the raptor paddock in jurassic park",
    unit: "minutes uneaten",
    sfw: true,
  },
  {
    text:
      "out of 100, what are the odds #player cries during the first ten minutes of up",
    unit: "percent chance of tears",
    sfw: true,
  },
  {
    text:
      "how many dollars would #player demand to hand their unlocked phone to this group for one hour",
    unit: "hush money dollars",
    sfw: true,
  },
  {
    text:
      "how many browser tabs is #player keeping alive right now like tiny neglected houseplants",
    unit: "doomed tabs",
    sfw: true,
  },
  {
    text:
      "if #player started a pyramid scheme, how many of us would buy in before asking a single question",
    unit: "downline recruits",
    sfw: true,
  },
  {
    text:
      "#player gets sent back to the year 1300 with nothing but their outfit and modern knowledge. how many days before a village either crowns them or chases them out with pitchforks",
    unit: "days as a suspicious stranger",
    sfw: true,
  },
  {
    text:
      "how many times a day do you pick your phone back up within one minute of putting it down",
    unit: "phone check relapses",
    sfw: true,
  },
  {
    text:
      "how many people has #player made laugh so hard they had to sit down",
    unit: "laughter casualties",
    sfw: true,
  },
  {
    text:
      "how many of #player's exes still think about them at least once a week",
    unit: "haunted exes",
    sfw: false,
  },
  {
    text:
      "how many minutes into a first date does #player unveil their most unhinged opinion",
    unit: "minutes of restraint",
    sfw: false,
  },
  {
    text:
      "how many dollars would #player pay right now for a pill that guarantees no hangovers for life",
    unit: "desperate dollars",
    sfw: false,
  },
  {
    text:
      "be honest, what is #player's body count... of mosquitoes slapped this summer",
    unit: "slain mosquitoes",
    sfw: false,
  },
  {
    text:
      "how many times can someone say 'circle back' in a single meeting before it legally becomes a crime",
    unit: "circle backs",
    sfw: true,
  },
  {
    text:
      "how much money would #player need to be paid to give up coffee for an entire year",
    unit: "dollars of caffeine ransom",
    sfw: true,
  },
  {
    text:
      "how many minutes into an all-hands does the first person secretly start answering emails",
    unit: "minutes of pretending to listen",
    sfw: true,
  },
  {
    text:
      "free bagels just got announced in the office slack. how many seconds until the kitchen is picked completely clean",
    unit: "seconds of bagel frenzy",
    sfw: true,
  },
  {
    text:
      "how many reply-all apologies get sent worldwide every single day",
    unit: "reply-all apologies",
    sfw: true,
  },
  {
    text:
      "how many seconds does a normal person spend re-reading a two-line email to the CEO before hitting send",
    unit: "seconds of pure panic",
    sfw: true,
  },
  {
    text:
      "how many pens has the average office worker accidentally taken home over their entire career",
    unit: "liberated pens",
    sfw: true,
  },
  {
    text:
      "how many donuts would it take to get the whole company to show up in person for a 7am monday meeting",
    unit: "bribery donuts",
    sfw: true,
  },
  {
    text:
      "how many total hours of #player's life have been lost to people saying 'you're on mute'",
    unit: "muted hours",
    sfw: true,
  },
  {
    text:
      "how many crumbs are living inside the average office keyboard right now",
    unit: "keyboard crumbs",
    sfw: true,
  },
  {
    text:
      "a meeting keeps getting extended 15 minutes at a time. how many extensions until #player just stands up and walks out on camera",
    unit: "meeting extensions",
    sfw: true,
  },
  {
    text:
      "how many drinks deep does #player get before volunteering for karaoke",
    unit: "liquid courage units",
    sfw: false,
  },
  {
    text:
      "how many exes' phone numbers could you still type from memory right now",
    unit: "haunting digits",
    sfw: false,
  },
  {
    text:
      "how many minutes should you wait to text back after a great first date so you seem chill but not dead",
    unit: "strategic minutes",
    sfw: false,
  },
  {
    text:
      "how many red flags can one person have before they stop being 'mysterious' and start being a cautionary tale",
    unit: "red flags",
    sfw: false,
  },
  {
    text:
      "how many hours long was your all-time record 'just one quick drink'",
    unit: "hours of just one drink",
    sfw: false,
  },
  {
    text:
      "how many times in your life have you announced 'i'm never drinking again' and fully meant it in the moment",
    unit: "broken promises",
    sfw: false,
  },
  {
    text:
      "how many minutes would #player last at their ex's wedding before giving a toast nobody asked for",
    unit: "minutes of composure",
    sfw: false,
  },
  {
    text:
      "how many dating app conversations have you let quietly die because replying started to feel like homework",
    unit: "abandoned chats",
    sfw: false,
  },
  {
    text:
      "how many minutes late can a date be before you're morally cleared to order appetizers without them",
    unit: "grace-period minutes",
    sfw: false,
  },
  {
    text:
      "it's 1am and #player's crush finally texts back with just 'hey'. how many friends does #player consult before sending a reply",
    unit: "members of the war council",
    sfw: false,
  },
];
